project:
  type: website
  output-dir: docs

website:
  title: "ASA Postdoc Association"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Mission & Goals"
        href: mission.qmd
      # - text: "About"
        # menu:
      - text: "Committee"
        href: people.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

