project:
  type: website
  output-dir: docs

website:
  title: "ASA Postdoc Association"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "About"
        menu:
        - text: "Vision"
        - text: "Excutive Committee"
          href: people.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

