---
title: "Advocate for Federal Data Access and Statistical Infrastructure"
subtitle: "Strengthen Our Collective Impact via Communication"
date: "2025-02-07"
categories: [advocay]
---

ASAPA is inspired by the advocacy effort from Dr. Steve Pierson and ASA regarding the current challenging situation to access federal data. Please sign the collective letters to advocate our foundamental rights as researcher.

Source: [https://community.amstat.org/discussion/communicating-your-concerns#bm93a55f18-661c-445f-9c76-fa1c3e176fe5](https://community.amstat.org/discussion/communicating-your-concerns#bm93a55f18-661c-445f-9c76-fa1c3e176fe5)


> Dear ASA Members,
> 
> Thank you to everyone who has shared concerns with the ASA so far. As [Ron and Ji-Hyun mentioned in their message on Monday](https://community.amstat.org/discussion/supporting-our-professional-community), we take these concerns seriously and are committed to providing concrete support. One key way we do this is through direct communication with Congress-via letters, meetings, and other outreach efforts. But your voices as individual constituents are just as crucial.
>
> To help facilitate engagement, I want to highlight two immediate opportunities to sign letters that will be sent to Congress:
>
> - **Letter on protecting and preserving public access to federal data**: https://docs.google.com/forms/d/e/1FAIpQLSdhiG2y74R19j0e0MdLsRtgZAuYDPiaJqU5nQEjywLneZVNxw/viewform?pli=1
> - **Letter on threats to our nation's economic statistical infrastructure**: https://docs.google.com/forms/d/e/1FAIpQLSf2P-WtW1a68GMn5gMUyTpYnIHrjWQ6WoWrXVAQj1wu1o3AyA/viewform?usp=sharing
> 
> These letters are open for both individual and organizational sign-ons. While ASA has already signed both, individual participation strengthens our collective impact. A high volume of signatures increases visibility and influence, so please consider adding your name and sharing these with your networks.
>       
> - Deadline for the first letter: Friday, February 7
>
> - Deadline for the second letter: Wednesday, February 12
>
> Beyond signing letters, direct communication with your Senators and Representative is even more impactful. Several organizations provide quick and easy ways to do this. For instance, the Association for American Cancer Institutes has this action page opposing federal funding freezes where one can edit their template message and have it sent to their elected officials based on their home address and zip code: https://www.votervoice.net/AACI/campaigns/120780/respond.
> 
> You can also contact your representatives directly through their websites or by calling their offices. The following instructions are from the [ASA Science Policy and Advocacy page](ASA Science Policy and Advocacy page):
>         
> **Call their offices.** You can find contact information on the House of Representatives website (or enter your ZIP code at www.house.gov/representatives/find) and Senate website.
> **Use the contact feature on your senators' and representative's websites.** See Option 1 for accessing these web pages.
> **Request a meeting in a district/state office or in Washington**: Meeting requests are typically handled through the member's scheduler, whose name and contact information can be obtained by calling the member's office. See ["Keys to a Successful Hill Meeting."](https://www.amstat.org/docs/default-source/amstat-documents/pol-successfulhillmeetingtips.pdf?v=1.1)
>
> Thank you for taking the time to make your voice heard. I will continue sharing additional advocacy opportunities in the coming days.
>
> Please contact me with any questions or suggestions ([spierson@amstat.org](mailto:spierson@amstat.org)) and I hope you will continue sharing your comments through the ASA anonymous [JotForm survey](https://form.jotform.com/zzlalo/member-input).