---
title: "Response to NIH Request For Information"
subtitle: "on Recommendations on Re-Envisioning U.S. Postdoctoral Research Training and Career Progression Within the Biomedical Research Enterprise"
date: "2024-10-22"
categories: [advocay]
---

**Recommendation 1.3 Part 1:** Limit the total number of years a person can be supported by NIH funds in a postdoctoral position to no more than 5 years.

-   Describe any potential benefits, opportunities, challenges and/or consequences to the postdoctoral workforce or the extramural research community if NIH were to limit total years of NIH-supported funding support for postdoctoral scholars.
-   Please describe any existing NIH or extramural institutional policies that could pose challenges for the implementation of a policy to limit aggregate NIH funding support for postdoctoral scholars.

**Response:** We do not expect this change would impact postdoctoral research fellows working in biostatistics. Currently, the fellowship duration is typically 1-3 years.

------------------------------------------------------------------------

**Recommendation 1.3 Part 2:** Limit the total number of years a person can be supported by NIH funds in a postdoctoral position to no more than 5 years.

-   Please describe any key NIH or extramural institutional policies, processes or resources that should be developed, improved or expanded to address any potential challenges associated with limiting aggregate funding support for postdoctoral scholars.

-   What mechanisms should be put into place by extramural institutions to support transitions for postdoctoral scholars nearing the end of the five-year period?

**Response:** The policies should clearly state cases that are eligible for exceptions to this rule and the process by which an exception is granted. For example, childbirth, immigration challenges, family care issues, illness, needing to change research groups, etc. may all necessitate additional time spent as a postdoctoral researcher.

Mechanisms to assist scholars nearing the end of their postdoctoral term could include a grace period of funding which covers transitionary periods. This funding could be accessible only via request.

------------------------------------------------------------------------

**Recommendation 2.2 Part 1:** Revise the K99/R00 mechanism to focus on ideas and creativity over productivity.

-   Describe any potential short- and long-term benefits and/or challenges to the postdoctoral workforce that may result from limiting the K99/R00 eligibility time frame to no more than 2 years of postdoctoral experience.

**Response:** Since postdoctoral scholars in the field of biostatistics typically are in their role for about 1-3 years, limiting the K99/R00 eligibility to no more than 2 years of experience would be reasonable for our field. However, we acknowledge it may be prohibitively difficult for other fields (e.g., those working with animal models). In addition, it may be worth considering how this limitation could be modified to accommodate extenuating circumstances, such as childbirth, family illness, caretaker responsibilities, etc., that may pull a scholar away from their work for an extended period of time.

Some challenges we recommend addressing are (1) the opportunity to resubmit and (2) the length of the review process. Currently, the K99/R00 mechanism is not realistic for postdocs in biostatistics if the award is not granted until the end of the third year (because it takes about a year from submission to funding), by which time most postdocs have secured other employment. The F99/K00/R00 proposed in the WG recommendations may be an attractive mechanism in biostatistics and similar quantitative fields. This would allow interested junior researchers to gain valuable grant writing experience without unnecessarily extending the length of the postdoctoral training.

------------------------------------------------------------------------

**Recommendation 2.2 Part 2:** Revise the K99/R00 mechanism to focus on ideas and creativity over productivity.

-   How should the K99/R00 mechanism and review criteria be revised to better emphasize creative ideas and innovation over research productivity? What specific criteria or metrics should be used to evaluate creativity and potential impact of applicants’ research proposals?

-   Provide input on key NIH and extramural institutional policies, processes or resources that may need to be developed or revised to ensure that changes to K99/R00 program eligibility do not negatively impact access to these awards to a broader range of postdoctoral scholars.

**Response:** We completely agree that the K99/R00 mechanism should focus on creativity over productivity. We propose to introduce interdisciplinary contribution as a dimension to measure creativity and innovation.

While we appreciate the possibility that future K99/R00 mechanisms would focus on creativity over productivity, we acknowledge the substantial challenge in developing a consensus definition of creativity across scientific fields, even within the same institution. Hence, we would recommend developing a clear guideline on how creativity would be evaluated for both applicants and reviewers.

------------------------------------------------------------------------

**Recommendation 4 Part 1:** Promote training and professional development of postdoctoral scholars and their mentors.

Provide suggestions/strategies for how NIH and extramural institutions can ensure that career and professional development training becomes an integrated and measured component of the postdoctoral experience. What policies and resources should institutions establish to ensure equitable access to career and professional development training for all postdoctoral scholars? How can institutions address barriers to participation, such as limited availability of training programs or conflicts with research obligations?

**Response:** One suggestion we have is to develop RCR training modules that better suit postdoctoral scholars in computational/quantitative fields. Currently, RCR training is focused on traditional bench science research, and misses the opportunity to discuss the ethical issues arising in data science and related fields. We recommend offering training in various formats, such as online/hybrid sessions, to accommodate different schedules for postdocs, especially those with families, and those who work remotely. We would also recommend recording sessions if possible.

Another challenge we anticipate postdocs face in participating in career and professional development is advisor buy-in. The NIH could provide funding for postdocs to access professional development opportunities. In addition, the NIH could partner with scientific professional organizations so that their events could count toward training. For example, in statistics and biostatistics, several organizations offer professional development opportunities, such as the American Statistical Association and the International Biometric Society. It would be great if scholars could complete their required professional development training through these organizations.

Finally, for fields such as biostatistics, interdisciplinary collaboration drives a fundamental component of our research. Training related to how to collaborate across fields-of-expertise would be very useful to scholars in our field.

------------------------------------------------------------------------

**Recommendation 4 Part 2:** Promote training and professional development of postdoctoral scholars and their mentors.

-   What specific skills and competencies are essential for individuals serving in the mentor role for postdoctoral scholars? How should institutions require and support mentor training to ensure the effective mentorship of postdoctoral scholars? Describe any necessary resources required by investigators and institutions to support the implementation of required training opportunities for mentors

-   Are there opportunities for collaboration between institutions, funding agencies, and professional organizations to enhance career and professional development opportunities for postdoctoral scholars? How can partnerships with industry, government agencies, and non-profit organizations contribute to the enrichment of postdoctoral training experiences?

**Response:** Mentors should be able to provide adequate resources/advice for postdocs, and a solid understanding of diverse career paths. Institutions should have structured mentor training programs that cover key skills and best practices for postdoctoral mentors. In general, postdocs are more independent but they are still in the training phase of their career. Therefore effective mentoring is still expected. Mentors should encourage postdocs to attend conferences, workshops, and provide regular feedback/discussions to a postdoc’s work, as well as help connect postdocs with collaborators. Clear mentorship guidelines can help standardize expectations and good mentors should be rewarded for their hard work. Funding agencies can offer grants to enhance mentorship training, while professional organizations can provide additional resources and networking opportunities. Collaborations between academic institutions will provide postdocs with more opportunities for networking and job searching; for collaborations with industry, postdocs can have broader experience and more information about potential job opportunities outside of academia, which will enrich the whole training experience.